"""Academic content grounded in the new PPT and the supplied report."""
import html

LINKS = {
    2: 'https://docs.google.com/spreadsheets/d/1dfdGAIqMdnXnEydWuhijhV5HpGcXEtei/edit?usp=sharing&ouid=112145322554055996042&rtpof=true&sd=true',
    7: 'https://docs.google.com/spreadsheets/d/1wfGL-WOqyl02a5UnGWo-ubaqN32m7rAN/edit?usp=sharing&ouid=112145322554055996042&rtpof=true&sd=true',
    8: 'https://docs.google.com/spreadsheets/d/16TgEx0DV49utu98v85XKixgbDCwXO7o9/edit?usp=sharing&ouid=112145322554055996042&rtpof=true&sd=true',
}

FORMATS = {
  2: {'case':'01','name':'Exámenes médicos ocupacionales','code':'O5.2.0.FO11','image':'format2', 'steps':[
    {'label':'Tipo y fecha','title':'Primero se registra el ingreso.','fields':[['Tipo de examen','Ingreso (I)'],['Realización','22/09/2026']], 'why':'El examen se realizó antes del inicio de labores, registrado para el 01/10/2026.'},
    {'label':'Trabajador y puesto','title':'Se identifica a quién y para qué puesto.','fields':[['Trabajador','Carlos Alberto Ramírez Torres · 32 años'],['Puesto','Ingeniero de mantenimiento mecánico (mina)']], 'why':'La evaluación se relaciona con los riesgos del puesto previsto: trabajo en altura.'},
    {'label':'Aptitud y restricción','title':'Apto con restricciones no significa no apto.','fields':[['Aptitud','Apto con restricciones'],['Restricción','No realizar trabajos en altura']], 'why':'La restricción se cumple mediante la reasignación a labores de oficina.'},
    {'label':'Vigencia y observación','title':'La vigencia también debe controlarse.','fields':[['Vencimiento registrado','22/09/2027'],['Observaciones de NO APTO','NA']], 'why':'Se usa NA porque el trabajador no fue declarado no apto. La fecha corresponde al registro del caso.'},
    {'label':'Resultado preventivo','title':'La decisión evita la exposición al riesgo.','fields':[['Área registrada','Oficina de Ingeniería (reasignado)'],['Resultado','Evaluar → restringir → reubicar']], 'why':'El registro acredita la evaluación y la decisión preventiva antes de exponer al trabajador a una caída.'},
  ]},
  7: {'case':'06','name':'Inducción, capacitación y simulacros','code':'O5.2.0.FO15','image':'format7', 'steps':[
    {'label':'Actividad registrada','title':'Dos actividades, un registro.','fields':[['Casillas marcadas','Capacitación + Simulacro de emergencia'],['Tema','Uso y manejo de extintores portátiles']], 'why':'El formato incluye inducción, capacitación, entrenamiento y simulacros; en este caso se registran capacitación y simulacro.'},
    {'label':'Fecha y responsable','title':'La actividad tiene fecha y capacitador.','fields':[['Fecha','25/09/2026'],['Capacitador','Ing. Jorge Luis Paredes Salazar · SSOMA']], 'why':'Identificar a la persona que impartió la actividad permite verificar quién la desarrolló.'},
    {'label':'Horas de formación','title':'Las cuatro horas tienen una distribución.','fields':[['Teoría','2 horas'],['Práctica + simulacro','1 hora + 1 hora']], 'why':'El total es 4 horas: teoría, práctica con extintores y simulacro de incendio.'},
    {'label':'Lista de participantes','title':'La asistencia se acredita con nombres y firmas.','fields':[['Participantes','20 trabajadores de 13 áreas'],['Evidencia','Apellidos, nombres, DNI, área y firma']], 'why':'La lista registra quién participó. El PPT y la tabla del informe indican 20 participantes.'},
    {'label':'Resultado verificable','title':'La capacitación deja evidencia.','fields':[['Observación','Participó en teoría, práctica y simulacro'],['Registro','N.° 001 · Minera Chinalco Perú S.A.']], 'why':'La empresa puede mostrar el tema, las horas, el capacitador y la asistencia en una inspección.'},
  ]},
  8: {'case':'07','name':'Auditorías del SG-SST','code':'O5.2.0.FO16','image':'format8', 'steps':[
    {'label':'Auditores','title':'La auditoría identifica a sus responsables.','fields':[['Auditor 1','Ing. Walter M. Cornejo Bustamante'],['Auditor 2','Lic. Karina E. Ayala Domínguez']], 'why':'El registro identifica a los auditores y sus números de registro, junto con los procesos revisados.'},
    {'label':'Fechas y alcance','title':'Cada fecha se vincula con un proceso.','fields':[['28/09/2026','Monitoreo de agentes de riesgo · mina y planta'],['29/09/2026','Inspección de extintores · almacén']], 'why':'Se incluyen los responsables del proceso: Luis Fernando Montes Rivera y Óscar Daniel Fuentes Paredes.'},
    {'label':'No conformidades','title':'Se registran dos incumplimientos.','fields':[['NC 1 · Mayor','Monitoreos sin actualizar por más de 12 meses'],['NC 2 · Menor','Un extintor sin revisión en el plazo']], 'why':'El caso clasifica el primero como mayor por su alcance general y el segundo como menor por ser puntual.'},
    {'label':'Acción y plazo','title':'El hallazgo necesita una corrección verificable.','fields':[['NC 1','30/10/2026 · En ejecución'],['NC 2','09/10/2026 · Pendiente']], 'why':'Cada acción tiene causa, medida, responsable, plazo y estado; el plan se explica en la siguiente pantalla.'},
    {'label':'Documentos de cierre','title':'El registro se acompaña de evidencia.','fields':[['Adjunto 1','Informe de auditoría con hallazgos y firma'],['Adjunto 2','Plan de acción para el cierre de las NC']], 'why':'Corregir el problema y verificar el resultado son parte del seguimiento del plan de acción.'},
  ]},
}

def image(name, alt, label=None, cls=''):
    return f'<button class="evidence {cls}" data-image="{name}" data-title="{html.escape(alt)}" aria-label="Ampliar: {html.escape(alt)}"><img src="../assets/{name}.webp" alt="{html.escape(alt)}" draggable="false"><span class="zoom-corner" aria-hidden="true">↗</span>{f"<span class='image-label'>{label}</span>" if label else ""}</button>'

def header(tag, title, lead='', cls=''):
    return f'<div class="section-heading {cls}" data-anim><p class="eyebrow">{tag}</p><h1>{title}</h1>{f"<p class='lead'>{lead}</p>" if lead else ""}</div>'

def field(label, value):
    return f'<div class="fact"><span>{label}</span><strong>{value}</strong></div>'

def format_body(number):
    f=FORMATS[number]
    buttons=''.join(f'<button class="step-button" data-step="{i}" aria-label="Paso {i+1}: {s["label"]}"><span>{i+1:02d}</span>{s["label"]}<i aria-hidden="true"></i></button>' for i,s in enumerate(f['steps']))
    return header(f'CASO {f["case"]} / REGISTRO COMPLETADO',f'FORMATO <em>{number:02d}</em>',f['name'])+f'''
      <div class="format-layout" data-format="{number}">
        <div class="document-card" data-anim>
          <div class="document-top"><span>{f['code']}</span><span>REGISTRO 001</span></div>
          {image(f['image'],f'Registro original del Formato {number}',f'Figura {3 if number==2 else 5 if number==7 else 6} · Imagen del PPT','document-image')}
          <div class="document-actions"><button class="button" data-view="{number}">Explorar registro <span>↗</span></button><a class="button ghost" href="{html.escape(LINKS[number])}" target="_blank" rel="noopener noreferrer">Abrir Google Sheets <span>↗</span></a></div>
        </div>
        <div class="guide-card" data-anim><div class="guide-top"><span>LECTURA GUIADA</span><span class="step-count">01 / 05</span></div>
          <div class="steps">{buttons}</div><div class="step-readout" aria-live="polite"></div>
          <p class="guide-hint">Recorre los pasos con el cursor o con las flechas →</p>
        </div>
      </div>'''

SLIDES=[]
def slide(id, title, theme, body, notes, format=None):
    SLIDES.append({'id':id,'title':title,'theme':theme,'body':body,'notes':notes,'format':format})

slide('portada','Registrar es prevenir','orange',f'''
  <div class="hero-layout"><div class="hero-copy" data-anim><p class="eyebrow">GRUPO 1 / SEGURIDAD INDUSTRIAL</p><h1>REGISTRAR<br>ES <span>PREVENIR.</span></h1><p class="hero-sub">Registros obligatorios del Sistema de Gestión de Seguridad y Salud en el Trabajo.</p><button class="button navy" data-goto="1">Comenzar la exposición <span>↗</span></button><div class="hero-meta">R.M. N.° 050-2013-TR <span>PIURA / 09.10.2026</span></div></div>
  <div class="hero-art" data-anim><div class="orbit" aria-hidden="true"></div><div class="hero-photo">{image('hero','Personal de la minera, imagen incluida en el PPT')}</div><div class="hero-stamp">SG<br>SST<span>DOCUMENTAR<br>PARA ACTUAR</span></div><div class="hero-caption">CASOS APLICADOS A<br><strong>MINERA CHINALCO PERÚ S.A.</strong></div></div></div>
''','Presentar el objetivo: demostrar el llenado correcto de tres registros del SG-SST. La exposición usa los casos 1, 6 y 7 de Minera Chinalco Perú S.A. Curso: Seminario de Habilidades Prácticas. Docente: Guisela Manira García Ruiz. Fecha del nuevo PPT: Piura, 9 de octubre de 2026.')

agenda=[('01','Marco normativo','La base legal de los registros.',2),('02','Una empresa','Los mismos datos en los tres casos.',3),('03','Evaluar antes','Caso 1 · Formato 2',4),('04','Formar y practicar','Caso 6 · Formato 7',7),('05','Auditar y corregir','Caso 7 · Formato 8',10),('06','Conectar la evidencia','Resumen, conclusiones y cierre.',14)]
slide('ruta','La ruta de la exposición','cream',header('EL RECORRIDO','TRES CASOS.<br>UNA MISMA <em>LÓGICA.</em>','Situación → registro → evidencia → decisión.')+'<div class="agenda-grid">'+''.join(f'<button class="agenda-card" data-goto="{t}" data-hover-nav data-anim><span class="big-index">{n}</span><div><h2>{a}</h2><p>{b}</p></div><span class="card-arrow">↗</span></button>' for n,a,b,t in agenda)+'</div>','Explicar la secuencia: primero normas y empresa; luego el examen médico, la capacitación y la auditoría. Cerrar comparando las evidencias. Mantener el cursor sobre una tarjeta para entrar o hacer clic para avanzar de inmediato.')

laws=[('01','LEY N.° 29783','Establece deberes de prevención del empleador.'),('02','D.S. N.° 005-2012-TR','El artículo 33 detalla los registros obligatorios.'),('03','R.M. N.° 050-2013-TR','Aprueba los formatos referenciales de los registros.'),('04','R.M. N.° 312-2011/MINSA','Define protocolos y criterios de aptitud médica.')]
slide('normas','Los registros tienen una base legal','navy',header('MARCO NORMATIVO','LA PREVENCIÓN<br>TAMBIÉN SE <em>DOCUMENTA.</em>')+'<div class="law-layout"><div class="law-list">'+''.join(f'<div class="law-item" data-anim><span>{n}</span><div><h2>{a}</h2><p>{b}</p></div></div>' for n,a,b in laws)+'</div><div class="legal-document" data-anim>'+image('law','Artículo 33 del D.S. N.° 005-2012-TR, registros resaltados','Figura 1 · Artículo 33')+'<p>Los registros b), g) y h) sustentan los tres casos.</p></div></div>','Explicar el aporte de cada norma. Abrir la Figura 1 para mostrar el artículo 33 y los registros resaltados: exámenes médicos, capacitación y auditorías. La información reproduce las fuentes aportadas; las referencias completas se encuentran al final.')

slide('empresa','Una empresa, tres registros','cream',header('EL CONTEXTO','UNA EMPRESA.<br>TRES <em>REGISTROS.</em>')+f'<div class="company-layout"><div class="company-photo" data-anim>{image("company","Foto grupal del personal de Minera Chinalco, incluida en el PPT","Imagen 1 · Personal operario")}</div><div class="company-data" data-anim><div class="company-name">MINERA CHINALCO<br>PERÚ S.A.</div><div class="company-stat"><strong>50</strong><span>TRABAJADORES<br>EN EL CENTRO LABORAL</span></div>{field("RUC","20506675457")}{field("Actividad","Minería metálica · cobre")}{field("Domicilio","Av. Santa Cruz N.° 180, primer piso, Torre A. San Isidro, Lima.")}</div></div>','Los tres registros pertenecen a la misma empresa. Señalar RUC, domicilio, actividad minera de cobre y 50 trabajadores. Estos datos deben ser coherentes en los tres formatos; no se cambia de empleador entre casos.')

slide('caso-1','Evaluar antes de trabajar en altura','orange',f'<div class="chapter-layout"><div class="chapter-copy" data-anim><p class="eyebrow">CASO 01 / FORMATO 02</p><h1>ANTES DE<br>SUBIR,<br><span>EVALUAR.</span></h1><p>El examen de ingreso identifica una restricción para trabajar en altura.</p><div class="result-chip">DECISIÓN: REASIGNAR A OFICINA</div></div><div class="chapter-photo" data-anim>{image("medical","Examen médico del trabajador, imagen incluida en el PPT","Imagen 2 · Evaluación médica")}</div><div class="chapter-number" aria-hidden="true">01</div></div>','Introducir el caso 1. Se contrata a un ingeniero para trabajar en altura. Antes de iniciar, se realiza el examen médico y se detecta una condición incompatible con ese riesgo. La decisión es reasignarlo a una oficina, tal como indica el caso.')

slide('caso-1-logica','La evaluación conduce a una decisión','cream',header('CASO 01 / LA DECISIÓN PREVENTIVA','EVALUAR. RESTRINGIR.<br><em>REUBICAR.</em>')+'<div class="logic-layout"><div class="logic-main"><div class="flow-cards"><div data-anim><span>01 / SITUACIÓN</span><h2>Un puesto con riesgo de altura.</h2><p>Se contrata a un ingeniero para trabajar en altura.</p></div><div data-anim><span>02 / HALLAZGO</span><h2>El examen detecta una restricción.</h2><p>La condición médica impide realizar ese trabajo.</p></div><div data-anim><span>03 / DECISIÓN</span><h2>La oficina elimina esa exposición.</h2><p>Se reasigna al trabajador antes de exponerlo al riesgo de caída.</p></div></div></div><div class="logic-aside" data-anim>'+image('case1','Enunciado del Caso 1','Figura 2 · Enunciado')+'<div class="reason-box"><span>¿POR QUÉ EL FORMATO 2?</span><p>Registra tipo de examen, fecha, aptitud y restricciones.</p></div></div></div>','Justificar el Formato 2: acredita la evaluación de ingreso y las restricciones aplicables al puesto. Diferenciar el examen, el hallazgo y la decisión del empleador. El objetivo preventivo es evitar la exposición al riesgo de caída.')
slide('formato-2','Cómo se llenó el Formato 2','cream',format_body(2),'Recorrer los cinco pasos con las flechas o el cursor. Explicar Ingreso I y fecha, trabajador y cargo, apto con restricciones, prohibición de altura y reasignación. El vencimiento es el consignado en el caso; NA corresponde a observaciones de NO APTO porque no fue declarado no apto. Usar Explorar registro para ampliar la imagen o leer el Excel completo.',2)

slide('caso-6','Aprender y practicar con extintores','navy',f'<div class="chapter-layout"><div class="chapter-copy" data-anim><p class="eyebrow">CASO 06 / FORMATO 07</p><h1>APRENDER.<br>PRACTICAR.<br><span>RESPONDER.</span></h1><p>La capacitación y el simulacro preparan al personal para un incendio.</p><div class="result-chip">TEORÍA + PRÁCTICA + SIMULACRO</div></div><div class="chapter-photo" data-anim>{image("training","Capacitación práctica en el uso de extintores, incluida en el PPT","Imagen 3 · Práctica con extintores")}</div><div class="chapter-number" aria-hidden="true">06</div></div>','Introducir el caso 6. La empresa realiza capacitación teórica y práctica sobre extintores y un simulacro de incendio. Se debe registrar la actividad y a quienes participaron. La imagen procede del nuevo PPT.')

slide('caso-6-logica','La formación necesita evidencia','cream',header('CASO 06 / EVIDENCIA DE FORMACIÓN','NO BASTA CON CAPACITAR.<br>HAY QUE <em>REGISTRAR.</em>')+'<div class="training-layout"><div class="training-main" data-anim><div class="hour-grid"><div><strong>2h</strong><span>TEORÍA</span></div><div><strong>1h</strong><span>PRÁCTICA</span></div><div><strong>1h</strong><span>SIMULACRO</span></div></div><p class="big-copy">Un registro reúne el tema, el capacitador, las horas y la lista de asistentes.</p><div class="participant-bar"><strong>20</strong><span>PARTICIPANTES<br>CON DATOS Y FIRMA</span></div></div><div class="logic-aside" data-anim>'+image('case67','Enunciado de los Casos 6 y 7','Figura 4 · Enunciado')+'<div class="reason-box"><span>¿POR QUÉ EL FORMATO 7?</span><p>Evidencia inducción, capacitación, entrenamiento y simulacros.</p></div></div></div>','Mostrar que las cuatro horas se distribuyen en 2 de teoría, 1 de práctica y 1 de simulacro. Se marcan capacitación y simulacro en un solo formato. La lista firmada es la evidencia de participación. Se usan 20 asistentes, como en el PPT y la tabla del informe.')
slide('formato-7','Cómo se llenó el Formato 7','cream',format_body(7),'Recorrer actividades marcadas, fecha y capacitador, cuatro horas, lista de 20 participantes de 13 áreas y evidencia de participación. Distinguir la actividad de la evidencia. El documento original contiene DNI y firmas; la vista de lectura permite ampliar las celdas del Excel.',7)

slide('caso-7','Auditar para corregir','orange',f'<div class="chapter-layout"><div class="chapter-copy" data-anim><p class="eyebrow">CASO 07 / FORMATO 08</p><h1>OBSERVAR.<br>CORREGIR.<br><span>VERIFICAR.</span></h1><p>La auditoría convierte los hallazgos en acciones con responsables y plazos.</p><div class="result-chip">DOS NO CONFORMIDADES</div></div><div class="chapter-photo audit-photo" data-anim>{image("audit","Auditoría en la minera, imagen incluida en el PPT","Imagen 4 · Auditoría")}</div><div class="chapter-number" aria-hidden="true">07</div></div>','Introducir el caso 7. La auditoría detecta monitoreos sin actualizar y un extintor sin revisión. El formato no se limita a enumerar problemas: debe permitir su corrección y seguimiento.')

slide('caso-7-hallazgos','Dos hallazgos con distinto alcance','cream',header('CASO 07 / LOS HALLAZGOS','DOS INCUMPLIMIENTOS.<br>DISTINTO <em>ALCANCE.</em>')+'''<div class="finding-grid"><article class="finding major" data-anim><div class="finding-top"><span>NC 01</span><span>MAYOR</span></div><strong class="finding-number">12<span>+ MESES</span></strong><h2>Monitoreos sin actualizar.</h2><p>Ruido, polvo, iluminación y agentes químicos. Afecta el control de los riesgos de la operación.</p></article><article class="finding minor" data-anim><div class="finding-top"><span>NC 02</span><span>MENOR</span></div><strong class="finding-number">01<span>EXTINTOR</span></strong><h2>Un control puntual incumplido.</h2><p>Extintor PQS ABC de 9 kg en el almacén general, sin revisión dentro del plazo.</p></article></div><div class="bottom-insight" data-anim><span>LA DEBILIDAD COMÚN</span><p>Falta de seguimiento programado.</p></div>''','El caso clasifica la NC1 como mayor porque afecta un control general de riesgos; la NC2 como menor porque corresponde a un equipo puntual. No generalizar esta clasificación a todos los casos. Las dos causas revelan falta de seguimiento programado.')
slide('formato-8','Cómo se llenó el Formato 8','cream',format_body(8),'Identificar los dos auditores, fechas y procesos auditados. Se cuentan dos no conformidades. Explicar la documentación adjunta: informe de auditoría y plan de acción con causa, medida, responsable, fecha y estado. La siguiente pantalla desarrolla las acciones.',8)

slide('plan-accion','Cerrar una no conformidad exige seguimiento','navy',header('CASO 07 / EL PLAN DE ACCIÓN','UN HALLAZGO<br>NO SE CIERRA <em>SOLO.</em>')+'''
<div class="action-grid"><article class="action-card" data-anim><div class="action-label"><span>NC 01 / MAYOR</span><span class="status orange-status">EN EJECUCIÓN</span></div><h2>Actualizar el monitoreo.</h2><dl><dt>CAUSA</dt><dd>No hay cronograma anual aprobado ni responsable de seguimiento.</dd><dt>MEDIDAS</dt><dd>Contratar laboratorio acreditado, actualizar registros, informar al Comité de SST y aprobar un cronograma anual.</dd></dl><div class="action-owner"><span>ING. LUIS F. MONTES RIVERA</span><strong>30.10.2026</strong></div></article><article class="action-card" data-anim><div class="action-label"><span>NC 02 / MENOR</span><span class="status yellow-status">PENDIENTE</span></div><h2>Restablecer la revisión.</h2><dl><dt>CAUSA</dt><dd>Falta de control del cronograma y de verificación por SST.</dd><dt>MEDIDAS</dt><dd>Inspeccionar y dar mantenimiento, actualizar la tarjeta e implementar una lista de verificación mensual.</dd></dl><div class="action-owner"><span>ING. ÓSCAR D. FUENTES PAREDES</span><strong>09.10.2026</strong></div></article></div><p class="action-footnote">Descripción → causa → medida → responsable → plazo → estado</p>
''','La auditoría necesita un plan verificable. Para la NC1, responsable Luis F. Montes Rivera, fecha 30/10/2026, en ejecución. Para la NC2, Óscar D. Fuentes Paredes, 09/10/2026, pendiente. No afirmar que las acciones ya se completaron: esos son los estados de los registros aportados. Resaltar cronogramas y listas mensuales para evitar recurrencia.')

slide('resumen','Tres formatos, tres evidencias','cream',header('LO QUE CONECTA LOS CASOS','CADA CASO DEJA<br>UNA <em>EVIDENCIA.</em>')+'''<div class="summary-grid"><button class="summary-card" data-goto="6" data-hover-nav data-anim><span>CASO 01</span><strong>02</strong><h2>Evaluación médica</h2><p>Aptitud con restricciones y reasignación.</p><i>EXAMEN → DECISIÓN ↗</i></button><button class="summary-card" data-goto="9" data-hover-nav data-anim><span>CASO 06</span><strong>07</strong><h2>Formación</h2><p>20 participantes, 4 horas y lista firmada.</p><i>ACTIVIDAD → EVIDENCIA ↗</i></button><button class="summary-card" data-goto="12" data-hover-nav data-anim><span>CASO 07</span><strong>08</strong><h2>Auditoría</h2><p>Dos no conformidades y su plan de acción.</p><i>HALLAZGO → CORRECCIÓN ↗</i></button></div><p class="summary-note">Mismo empleador: Minera Chinalco Perú S.A. / Registro N.° 001</p>''','Comparar la función de los registros: examen y decisión preventiva, capacitación y asistencia, auditoría y acciones correctivas. Los tres pertenecen al mismo empleador y al registro 001. Las tarjetas permiten volver a los formatos para responder preguntas.')

conclusions=[('Elegir el formato correcto.','Cada situación exige un registro que corresponda a la actividad.'),('Completar la evidencia.','Fecha, responsable y firma cuando corresponde.'),('Prevenir antes de exponer.','El examen de ingreso permitió una reasignación segura.'),('Demostrar la formación.','La capacitación y el simulacro quedaron documentados.'),('Dar seguimiento al hallazgo.','Una no conformidad necesita causa, medida, responsable y plazo.')]
slide('conclusiones','Documentar permite demostrar y actuar','cream',header('CONCLUSIONES','LA EVIDENCIA<br>PERMITE <em>ACTUAR.</em>')+'<div class="conclusion-list">'+''.join(f'<div data-anim><span>{i+1:02d}</span><h2>{a}</h2><p>{b}</p></div>' for i,(a,b) in enumerate(conclusions))+'</div>','Presentar las cinco conclusiones. La documentación sirve cuando es completa y se vincula con decisiones de prevención y seguimiento. Conectar cada conclusión con el caso correspondiente, en lugar de leerla sin explicación.')

recommendations=[('01','EXÁMENES','Programar evaluaciones periódicas y controlar el vencimiento de cada trabajador.'),('02','CAPACITACIÓN','Incluir extintores en el plan anual y repetir los simulacros.'),('03','CRONOGRAMAS','Aprobar el monitoreo de riesgos y las inspecciones, con responsables.'),('04','SEGUIMIENTO','Verificar cada medida del plan hasta que figure como realizada.')]
slide('recomendaciones','Programar, formar y verificar','orange',header('RECOMENDACIONES','EL SIGUIENTE PASO<br>ES <em>PROGRAMAR.</em>')+'<div class="recommendation-grid">'+''.join(f'<article data-anim><span>{n}</span><h2>{a}</h2><p>{b}</p></article>' for n,a,b in recommendations)+'</div>','Recomendar cuatro líneas de trabajo: exámenes y vencimientos; capacitación anual y simulacros; cronogramas con responsables; seguimiento hasta cerrar medidas. Evitar que las acciones sean solo reacciones inmediatas.')

members=['Josselyn Ariana Vilas Velásquez','Anderson Jair Varona Osorio','Iilder Branderly Merino Zurita','Francisco Adrianzen Rivera','Luis Felipe Ancajima Sullón']
slide('equipo','Gracias y preguntas','navy',header('GRUPO 1 / SEGURIDAD INDUSTRIAL','GRACIAS.<br>ABRIMOS LAS <em>PREGUNTAS.</em>')+'<div class="team-layout"><div class="member-list">'+''.join(f'<div data-anim><span>{i+1:02d}</span><p>{name}</p></div>' for i,name in enumerate(members))+'</div><div class="team-art" data-anim>'+image('thanks','Imagen de cierre incluida en el PPT')+'<p>Seminario de Habilidades Prácticas<br>Docente: Guisela Manira García Ruiz</p></div></div>','Agradecer y abrir preguntas. La nueva presentación contiene cinco integrantes, que se conservan en esta página. Para responder sobre los casos, usar el índice o las tarjetas del resumen para volver al registro específico.')

refs=[('2011','Congreso de la República del Perú','Ley N.° 29783, Ley de Seguridad y Salud en el Trabajo.','https://cdn.www.gob.pe/uploads/document/file/571762/Ley_N__29783.pdf?v=1585259556'),('2012','Presidencia de la República del Perú','D.S. N.° 005-2012-TR, Reglamento de la Ley de Seguridad y Salud en el Trabajo.','https://www.gob.pe/institucion/presidencia/normas-legales/462577-005-2012-tr'),('2013','Ministerio de Trabajo y Promoción del Empleo','R.M. N.° 050-2013-TR, formatos referenciales de los registros obligatorios.','https://www.gob.pe/institucion/mtpe/normas-legales/288031-050-2013-tr'),('2011','Ministerio de Salud','R.M. N.° 312-2011/MINSA, protocolos de exámenes médicos ocupacionales.','https://www.gob.pe/institucion/minsa/normas-legales/243792-312-2011-minsa-MINSA')]
slide('referencias','Referencias bibliográficas','cream',header('FUENTES DE LA PRESENTACIÓN','LA BASE DE<br>NUESTRO <em>TRABAJO.</em>')+'<div class="reference-list">'+''.join(f'<a href="{html.escape(url)}" target="_blank" rel="noopener noreferrer" data-anim><span>{year}</span><div><h2>{who}</h2><p>{what}</p></div><i>↗</i></a>' for year,who,what,url in refs)+'</div><div class="reference-end"><span>Fuentes bibliográficas incluidas en el nuevo PPT.</span><button class="button" data-goto="0">Volver al inicio ↗</button></div>','Las referencias corresponden a la nueva presentación. Se pueden abrir las fuentes desde los enlaces. También se conserva la relación con la R.M. 050-2013-TR y los formatos 2, 7 y 8. Esta es la última pantalla.')
